/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Dialog.java to edit this template
 */
package Interfaz;

import java.awt.Label;

/**
 *
 * @author MULTI
 */

public class sionodialog extends java.awt.Dialog {
boolean respuesta=false;
    /**
     * Creates new form sionodialog
     */
    public sionodialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panel1 = new java.awt.Panel();
        siB = new java.awt.Button();
        noB = new java.awt.Button();
        panel2 = new java.awt.Panel();
        txtL = new java.awt.Label();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        panel1.setLayout(new java.awt.GridBagLayout());

        siB.setLabel("SI");
        siB.setMinimumSize(new java.awt.Dimension(36, 28));
        siB.setPreferredSize(new java.awt.Dimension(36, 28));
        siB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siBActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(4, 23, 4, 23);
        panel1.add(siB, gridBagConstraints);

        noB.setLabel("NO");
        noB.setMinimumSize(new java.awt.Dimension(36, 28));
        noB.setPreferredSize(new java.awt.Dimension(36, 28));
        noB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noBActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(4, 23, 4, 23);
        panel1.add(noB, gridBagConstraints);

        add(panel1, java.awt.BorderLayout.SOUTH);

        panel2.setLayout(new java.awt.GridBagLayout());

        txtL.setText("label1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(14, 23, 14, 14);
        panel2.add(txtL, gridBagConstraints);

        add(panel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
      
    }//GEN-LAST:event_closeDialog

    private void siBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siBActionPerformed
        respuesta=true;
        dispose();
    }//GEN-LAST:event_siBActionPerformed

    private void noBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noBActionPerformed
        respuesta=false;
        dispose();
    }//GEN-LAST:event_noBActionPerformed

    public boolean isRespuesta() {
        return respuesta;
    }

    public void setTxtL(String txtL) {
        this.txtL.setText(txtL);
        pack();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                sionodialog dialog = new sionodialog(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button noB;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private java.awt.Button siB;
    private java.awt.Label txtL;
    // End of variables declaration//GEN-END:variables
}
